smbus: Fix printf format
smbus.c:14:19: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Werror=format=]
|    14 | #define pr_fmt(x) "smbus: " x
|       |                   ^~~~~~~~~
libmctp-log.h:21:27: note: in expansion of macro 'pr_fmt'
|    21 |  mctp_prlog(MCTP_LOG_ERR, pr_fmt(fmt), ##__VA_ARGS__)
|       |                           ^~~~~~
smbus.c:356:3: note: in expansion of macro 'mctp_prerr'
|   356 |   mctp_prerr("Got smbus payload sized %lu, expecting %d",
|       |   ^~~~~~~~~~
| cc1: all warnings being treated as errors

Tested: No functional changes. The warning no longer occurs.

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>
Change-Id: I1afdf70526d8e761d2e90b17ddd146b45a9024b1