astpcie: Fix cast issues
astpcie.c: In function 'mctp_astpcie_get_eid_info_ioctl':
| astpcie.c:44:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
|    44 |  get_eid_info.ptr = (uint64_t)eid_info;
|       |                     ^
astpcie.c:48:20: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
|    48 |   memcpy(eid_info, (void *)get_eid_info.ptr, get_eid_info.count);
|       |                    ^
astpcie.c: In function 'mctp_astpcie_set_eid_info_ioctl':
astpcie.c:59:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
|    59 |  set_eid_info.ptr = (uint64_t)eid_info;
|       |                     ^
| cc1: all warnings being treated as errors

Tested: No regression was found. The warnings no longer occur.

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>
Change-Id: I7594f682a5b78f91aedff32679af310a71ecf17c