mctp-astpcie-discovery: Fix uninitialized variable
mctp-astpcie-discovery.c:188:24: error: 'req.hdr.rq_dgram_inst' is used uninitialized in this function [-Werror=uninitialized]
  188 |  req.hdr.rq_dgram_inst |= MCTP_CTRL_HDR_FLAG_REQUEST;
cc1: all warnings being treated as errors

Tested: No functional changes. The warning no longer occurs.

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>
Change-Id: I130acff67c8bdaf58d9ab9cb2dca5ece81b2fd01