astpcie: Remove unused variables
Resolve compiler warnings:
astpcie.c:217:19: error: unused variable 'mctp_hdr' [-Werror=unused-variable]
  217 |  struct mctp_hdr *mctp_hdr = mctp_pktbuf_hdr(pkt);
      |                   ^~~~~~~~
astpcie.c:296:19: error: variable 'mctp_hdr' set but not used [-Werror=unused-but-set-variable]
  296 |  struct mctp_hdr *mctp_hdr;
      |                   ^~~~~~~~
cc1: all warnings being treated as errors

Tested: No functional changes. The warnings no longer occur.

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>
Change-Id: I72645b29dab5e7fc2a3ae01b1e8816364b513ccf