test_astpcie: Remove unused variables
test_astpcie.c:132:13: warning: unused variable 'write_index' [-Wunused-variable]
        static int write_index;
                   ^
test_astpcie.c:276:35: error: unused variable 'pkt_prv' [-Wunused-variable]
        struct mctp_astpcie_pkt_private *pkt_prv =
                                         ^
2 warnings generated.

Tested: No functional changes. The warnings no longer occur.

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>
Change-Id: I2faff8e92e592236c5dcdeeebba311040f4900f0